In [1]:
import pandas as pd
import re

df = pd.read_csv(r"C:\Users\Priyansh Singh\Desktop\Job Market\data\processed\jobs_for_model.csv")

In [2]:
df

,title,company,posted_date,employment_type,description,salary_avg,city,seniority_level,clean_role,clean_title,Unnamed: 10,clean_seniority
0,data analyst predictive analytics india x d...,Boston Consulting Group,01-12-2025,full-time,Locations: Bengaluru | Gurgaon\n\nWho We Are\n...,3.0,Gurugram,mid,"analytics engineer, data analyst",Data Analyst Predictive Analytics,NaN,mid
1,data analyst trainee,SparkNovaTechSolutions,02-12-2025,full-time,ABOUT THE ROLE\n\nWe are seeking a highly moti...,7.0,Jaipur,mid,"ai engineer, analytics engineer, data analyst,...",Data Analyst Trainee,NaN,junior
2,sr. data analyst adtech/omnichannel remote ...,Jobgether,01-12-2025,full-time,"Sr. Data Analyst, AdTech/Omnichannel (Remote, ...",1.0,IN,senior,"analytics engineer, data analyst",Senior Data Analyst /,NaN,senior
3,data analyst ecommerce & d2c insights,Wholsum Foods (Slurrp Farm and Mille),02-12-2025,full-time,Job Description: Data Analyst - Ecommerce & D2...,4.5,Gurugram,mid,"analytics engineer, data analyst",Data Analyst & D2C,NaN,mid
4,senior data analyst payments,Roku,NaN,full-time,Teamwork makes the stream work.\n\nRoku is cha...,1.0,Bengaluru,senior,"analytics engineer, data analyst",Senior Data Analyst Payments,NaN,senior
...,...,...,...,...,...,...,...,...,...,...,...,...
1382,data engineer python pyspark panda,LTIMindtree,01-12-2025,full-time,**Role Overview:**\n\nAs a Data Engineer with ...,7.5,Hyderabad,mid,data engineer,Data Engineer Python Pyspark Panda,NaN,mid
1383,lead tech python infra,D. E. Shaw India,03-12-2025,full-time,We are looking for a Software Developer to joi...,7.0,Hyderabad,lead,other,Lead Tech Python Infra,NaN,senior
1384,senior python developer,Luxoft,30-11-2025,full-time,Project description\n\nWe're seeking a strong ...,6.0,Hyderabad,senior,python developer,Senior Python Developer,NaN,senior
1385,python developer with dagster,Staffington Global,25-11-2025,full-time,Job Description:-\n\nJob Role: Python Develope...,5.0,Hyderabad,mid,python developer,Python Developer With Dagster,NaN,mid
1386,python developer with azure,People Prime Worldwide,28-11-2025,full-time,You are a skilled and motivated Python Develop...,9.0,Hyderabad,mid,python developer,Python Developer With Azure,NaN,mid

In [3]:
skill_map = {
    "data analyst": ["python", "sql", "excel", "tableau", "power bi", "statistics", "data cleaning", "eda", "postgresql", "mysql"],
    "business analyst": ["sql", "excel", "power bi", "tableau", "requirements gathering", "business strategy", "documentation", "stakeholder communication"],
    "product analyst": ["sql", "python", "a/b testing", "tableau", "product metrics", "experimentation", "dashboards"],
    "operations analyst": ["excel", "sql", "process optimization", "kpi analysis", "tableau", "forecasting"],
    "marketing analyst": ["sql", "python", "google analytics", "marketing metrics", "tableau", "excel"],
    "finance analyst": ["excel", "sql", "forecasting", "financial modeling", "statistics", "power bi"],
    "risk analyst": ["sql", "python", "risk modeling", "statistics", "excel", "regression analysis"],
    "reporting analyst": ["power bi", "tableau", "excel", "sql", "dashboarding", "kpi reporting"],

    "bi analyst": ["power bi", "tableau", "sql", "dax", "data modeling", "ssrs", "ssas", "excel"],
    "analytics engineer": ["sql", "dbt", "python", "snowflake", "airflow", "bigquery", "data modeling"],

    "data scientist": ["python", "machine learning", "statistics", "data preprocessing", "tensorflow", "pytorch", "feature engineering", "sql", "scikit-learn"],
    "statistician": ["statistics", "r", "python", "probability", "regression", "anova", "hypothesis testing"],
    "mathematician": ["linear algebra", "probability", "optimization", "python", "statistics"],

    "ml engineer": ["python", "machine learning", "mlops", "docker", "kubernetes", "aws", "tensorflow", "pytorch", "airflow", "feature store"],
    "ai engineer": ["python", "deep learning", "transformers", "gen ai", "llms", "tensorflow", "pytorch", "huggingface"],
    "deep learning engineer": ["python", "pytorch", "tensorflow", "cnn", "rnn", "transformers", "opencv"],
    "computer vision engineer": ["opencv", "pytorch", "tensorflow", "image processing", "yolo", "segmentation"],
    "nlp engineer": ["nlp", "llms", "transformers", "bert", "huggingface", "python", "text preprocessing"],

    "data engineer": ["python", "sql", "spark", "airflow", "aws", "azure", "gcp", "kafka", "snowflake", "data pipelines"],
    "data architect": ["data modeling", "aws", "azure", "gcp", "snowflake", "db design", "data governance"],
    "cloud architect": ["aws", "azure", "gcp", "terraform", "docker", "kubernetes", "cloud security"],
    "solution architect": ["systems design", "cloud architecture", "api design", "scalability", "microservices"],
    "analytics architect": ["data modeling", "bi tools", "cloud", "sql", "data strategy"],

    "python developer": ["python", "django", "flask", "fastapi", "rest api", "git", "sql", "docker"],
    "software engineer": ["java", "python", "data structures", "system design", "git", "docker", "sql"],

    "data analyst trainee": ["excel", "sql", "python basics", "tableau", "statistics basics"],
    "intern": ["python", "sql", "excel"],

    "other": ["python", "sql", "excel"]
}

In [4]:
def assign_skills(role: str):
    r = str(role).lower()
    for key in skill_map:
        if key in r:
            return ", ".join(skill_map[key])
    return ", ".join(skill_map["other"])

df["skills"] = df["clean_role"].apply(assign_skills)

In [5]:
df

,title,company,posted_date,employment_type,description,salary_avg,city,seniority_level,clean_role,clean_title,Unnamed: 10,clean_seniority,skills
0,data analyst predictive analytics india x d...,Boston Consulting Group,01-12-2025,full-time,Locations: Bengaluru | Gurgaon\n\nWho We Are\n...,3.0,Gurugram,mid,"analytics engineer, data analyst",Data Analyst Predictive Analytics,NaN,mid,"python, sql, excel, tableau, power bi, statist..."
1,data analyst trainee,SparkNovaTechSolutions,02-12-2025,full-time,ABOUT THE ROLE\n\nWe are seeking a highly moti...,7.0,Jaipur,mid,"ai engineer, analytics engineer, data analyst,...",Data Analyst Trainee,NaN,junior,"python, sql, excel, tableau, power bi, statist..."
2,sr. data analyst adtech/omnichannel remote ...,Jobgether,01-12-2025,full-time,"Sr. Data Analyst, AdTech/Omnichannel (Remote, ...",1.0,IN,senior,"analytics engineer, data analyst",Senior Data Analyst /,NaN,senior,"python, sql, excel, tableau, power bi, statist..."
3,data analyst ecommerce & d2c insights,Wholsum Foods (Slurrp Farm and Mille),02-12-2025,full-time,Job Description: Data Analyst - Ecommerce & D2...,4.5,Gurugram,mid,"analytics engineer, data analyst",Data Analyst & D2C,NaN,mid,"python, sql, excel, tableau, power bi, statist..."
4,senior data analyst payments,Roku,NaN,full-time,Teamwork makes the stream work.\n\nRoku is cha...,1.0,Bengaluru,senior,"analytics engineer, data analyst",Senior Data Analyst Payments,NaN,senior,"python, sql, excel, tableau, power bi, statist..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,data engineer python pyspark panda,LTIMindtree,01-12-2025,full-time,**Role Overview:**\n\nAs a Data Engineer with ...,7.5,Hyderabad,mid,data engineer,Data Engineer Python Pyspark Panda,NaN,mid,"python, sql, spark, airflow, aws, azure, gcp, ..."
1383,lead tech python infra,D. E. Shaw India,03-12-2025,full-time,We are looking for a Software Developer to joi...,7.0,Hyderabad,lead,other,Lead Tech Python Infra,NaN,senior,"python, sql, excel"
1384,senior python developer,Luxoft,30-11-2025,full-time,Project description\n\nWe're seeking a strong ...,6.0,Hyderabad,senior,python developer,Senior Python Developer,NaN,senior,"python, django, flask, fastapi, rest api, git,..."
1385,python developer with dagster,Staffington Global,25-11-2025,full-time,Job Description:-\n\nJob Role: Python Develope...,5.0,Hyderabad,mid,python developer,Python Developer With Dagster,NaN,mid,"python, django, flask, fastapi, rest api, git,..."
1386,python developer with azure,People Prime Worldwide,28-11-2025,full-time,You are a skilled and motivated Python Develop...,9.0,Hyderabad,mid,python developer,Python Developer With Azure,NaN,mid,"python, django, flask, fastapi, rest api, git,..."

In [6]:
# Step A — get unique skills from skill_map
all_skills = sorted({
    skill.strip().lower()
    for skills in skill_map.values()
    for skill in skills
})

# Step B — clean skill name to valid column
def skill_to_colname(skill):
    return "skill_" + re.sub(r"[^A-Za-z0-9]+", "_", skill).strip("_").lower()

skills_lower = df["skills"].str.lower().fillna("")

# Step C — create a 0/1 column for every skill
for skill in all_skills:
    colname = skill_to_colname(skill)
    # match skill as a word or phrase
    pattern = r"\b" + re.escape(skill) + r"\b"
    df[colname] = skills_lower.str.contains(pattern, regex=True).astype(int)

In [7]:
df

,title,company,posted_date,employment_type,description,salary_avg,city,seniority_level,clean_role,clean_title,...,skill_statistics,skill_statistics_basics,skill_system_design,skill_systems_design,skill_tableau,skill_tensorflow,skill_terraform,skill_text_preprocessing,skill_transformers,skill_yolo
0,data analyst predictive analytics india x d...,Boston Consulting Group,01-12-2025,full-time,Locations: Bengaluru | Gurgaon\n\nWho We Are\n...,3.0,Gurugram,mid,"analytics engineer, data analyst",Data Analyst Predictive Analytics,...,1,0,0,0,1,0,0,0,0,0
1,data analyst trainee,SparkNovaTechSolutions,02-12-2025,full-time,ABOUT THE ROLE\n\nWe are seeking a highly moti...,7.0,Jaipur,mid,"ai engineer, analytics engineer, data analyst,...",Data Analyst Trainee,...,1,0,0,0,1,0,0,0,0,0
2,sr. data analyst adtech/omnichannel remote ...,Jobgether,01-12-2025,full-time,"Sr. Data Analyst, AdTech/Omnichannel (Remote, ...",1.0,IN,senior,"analytics engineer, data analyst",Senior Data Analyst /,...,1,0,0,0,1,0,0,0,0,0
3,data analyst ecommerce & d2c insights,Wholsum Foods (Slurrp Farm and Mille),02-12-2025,full-time,Job Description: Data Analyst - Ecommerce & D2...,4.5,Gurugram,mid,"analytics engineer, data analyst",Data Analyst & D2C,...,1,0,0,0,1,0,0,0,0,0
4,senior data analyst payments,Roku,NaN,full-time,Teamwork makes the stream work.\n\nRoku is cha...,1.0,Bengaluru,senior,"analytics engineer, data analyst",Senior Data Analyst Payments,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,data engineer python pyspark panda,LTIMindtree,01-12-2025,full-time,**Role Overview:**\n\nAs a Data Engineer with ...,7.5,Hyderabad,mid,data engineer,Data Engineer Python Pyspark Panda,...,0,0,0,0,0,0,0,0,0,0
1383,lead tech python infra,D. E. Shaw India,03-12-2025,full-time,We are looking for a Software Developer to joi...,7.0,Hyderabad,lead,other,Lead Tech Python Infra,...,0,0,0,0,0,0,0,0,0,0
1384,senior python developer,Luxoft,30-11-2025,full-time,Project description\n\nWe're seeking a strong ...,6.0,Hyderabad,senior,python developer,Senior Python Developer,...,0,0,0,0,0,0,0,0,0,0
1385,python developer with dagster,Staffington Global,25-11-2025,full-time,Job Description:-\n\nJob Role: Python Develope...,5.0,Hyderabad,mid,python developer,Python Developer With Dagster,...,0,0,0,0,0,0,0,0,0,0
1386,python developer with azure,People Prime Worldwide,28-11-2025,full-time,You are a skilled and motivated Python Develop...,9.0,Hyderabad,mid,python developer,Python Developer With Azure,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df=df.drop(columns=["posted_date","description","company","title"])

In [9]:
df

,employment_type,salary_avg,city,seniority_level,clean_role,clean_title,Unnamed: 10,clean_seniority,skills,skill_a_b_testing,...,skill_statistics,skill_statistics_basics,skill_system_design,skill_systems_design,skill_tableau,skill_tensorflow,skill_terraform,skill_text_preprocessing,skill_transformers,skill_yolo
0,full-time,3.0,Gurugram,mid,"analytics engineer, data analyst",Data Analyst Predictive Analytics,NaN,mid,"python, sql, excel, tableau, power bi, statist...",0,...,1,0,0,0,1,0,0,0,0,0
1,full-time,7.0,Jaipur,mid,"ai engineer, analytics engineer, data analyst,...",Data Analyst Trainee,NaN,junior,"python, sql, excel, tableau, power bi, statist...",0,...,1,0,0,0,1,0,0,0,0,0
2,full-time,1.0,IN,senior,"analytics engineer, data analyst",Senior Data Analyst /,NaN,senior,"python, sql, excel, tableau, power bi, statist...",0,...,1,0,0,0,1,0,0,0,0,0
3,full-time,4.5,Gurugram,mid,"analytics engineer, data analyst",Data Analyst & D2C,NaN,mid,"python, sql, excel, tableau, power bi, statist...",0,...,1,0,0,0,1,0,0,0,0,0
4,full-time,1.0,Bengaluru,senior,"analytics engineer, data analyst",Senior Data Analyst Payments,NaN,senior,"python, sql, excel, tableau, power bi, statist...",0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,full-time,7.5,Hyderabad,mid,data engineer,Data Engineer Python Pyspark Panda,NaN,mid,"python, sql, spark, airflow, aws, azure, gcp, ...",0,...,0,0,0,0,0,0,0,0,0,0
1383,full-time,7.0,Hyderabad,lead,other,Lead Tech Python Infra,NaN,senior,"python, sql, excel",0,...,0,0,0,0,0,0,0,0,0,0
1384,full-time,6.0,Hyderabad,senior,python developer,Senior Python Developer,NaN,senior,"python, django, flask, fastapi, rest api, git,...",0,...,0,0,0,0,0,0,0,0,0,0
1385,full-time,5.0,Hyderabad,mid,python developer,Python Developer With Dagster,NaN,mid,"python, django, flask, fastapi, rest api, git,...",0,...,0,0,0,0,0,0,0,0,0,0
1386,full-time,9.0,Hyderabad,mid,python developer,Python Developer With Azure,NaN,mid,"python, django, flask, fastapi, rest api, git,...",0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df = df.drop(columns=[
    "clean_title",
    "Unnamed: 10"
], errors="ignore")

In [11]:
df

,employment_type,salary_avg,city,seniority_level,clean_role,clean_seniority,skills,skill_a_b_testing,skill_airflow,skill_anova,...,skill_statistics,skill_statistics_basics,skill_system_design,skill_systems_design,skill_tableau,skill_tensorflow,skill_terraform,skill_text_preprocessing,skill_transformers,skill_yolo
0,full-time,3.0,Gurugram,mid,"analytics engineer, data analyst",mid,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,1,0,0,0,1,0,0,0,0,0
1,full-time,7.0,Jaipur,mid,"ai engineer, analytics engineer, data analyst,...",junior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,full-time,1.0,IN,senior,"analytics engineer, data analyst",senior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,full-time,4.5,Gurugram,mid,"analytics engineer, data analyst",mid,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,full-time,1.0,Bengaluru,senior,"analytics engineer, data analyst",senior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,full-time,7.5,Hyderabad,mid,data engineer,mid,"python, sql, spark, airflow, aws, azure, gcp, ...",0,1,0,...,0,0,0,0,0,0,0,0,0,0
1383,full-time,7.0,Hyderabad,lead,other,senior,"python, sql, excel",0,0,0,...,0,0,0,0,0,0,0,0,0,0
1384,full-time,6.0,Hyderabad,senior,python developer,senior,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
1385,full-time,5.0,Hyderabad,mid,python developer,mid,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,0
1386,full-time,9.0,Hyderabad,mid,python developer,mid,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df["clean_seniority"] = df["clean_seniority"].fillna(df["seniority_level"])

In [13]:
df["primary_role"] = df["clean_role"].str.split(",").str[0].str.strip().str.lower()

In [14]:
df

,employment_type,salary_avg,city,seniority_level,clean_role,clean_seniority,skills,skill_a_b_testing,skill_airflow,skill_anova,...,skill_statistics_basics,skill_system_design,skill_systems_design,skill_tableau,skill_tensorflow,skill_terraform,skill_text_preprocessing,skill_transformers,skill_yolo,primary_role
0,full-time,3.0,Gurugram,mid,"analytics engineer, data analyst",mid,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
1,full-time,7.0,Jaipur,mid,"ai engineer, analytics engineer, data analyst,...",junior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,ai engineer
2,full-time,1.0,IN,senior,"analytics engineer, data analyst",senior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
3,full-time,4.5,Gurugram,mid,"analytics engineer, data analyst",mid,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
4,full-time,1.0,Bengaluru,senior,"analytics engineer, data analyst",senior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,full-time,7.5,Hyderabad,mid,data engineer,mid,"python, sql, spark, airflow, aws, azure, gcp, ...",0,1,0,...,0,0,0,0,0,0,0,0,0,data engineer
1383,full-time,7.0,Hyderabad,lead,other,senior,"python, sql, excel",0,0,0,...,0,0,0,0,0,0,0,0,0,other
1384,full-time,6.0,Hyderabad,senior,python developer,senior,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,python developer
1385,full-time,5.0,Hyderabad,mid,python developer,mid,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,python developer
1386,full-time,9.0,Hyderabad,mid,python developer,mid,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,python developer

In [15]:
# if any missing role/seniority, fill with 'other' / 'mid'
df["clean_role"] = df["clean_role"].fillna("other")
df["clean_seniority"] = df["clean_seniority"].fillna(df["seniority_level"]).fillna("mid")

# primary role = first role
df["primary_role"] = df["clean_role"].str.split(",").str[0].str.strip().str.lower()

In [16]:
df

,employment_type,salary_avg,city,seniority_level,clean_role,clean_seniority,skills,skill_a_b_testing,skill_airflow,skill_anova,...,skill_statistics_basics,skill_system_design,skill_systems_design,skill_tableau,skill_tensorflow,skill_terraform,skill_text_preprocessing,skill_transformers,skill_yolo,primary_role
0,full-time,3.0,Gurugram,mid,"analytics engineer, data analyst",mid,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
1,full-time,7.0,Jaipur,mid,"ai engineer, analytics engineer, data analyst,...",junior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,ai engineer
2,full-time,1.0,IN,senior,"analytics engineer, data analyst",senior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
3,full-time,4.5,Gurugram,mid,"analytics engineer, data analyst",mid,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
4,full-time,1.0,Bengaluru,senior,"analytics engineer, data analyst",senior,"python, sql, excel, tableau, power bi, statist...",0,0,0,...,0,0,0,1,0,0,0,0,0,analytics engineer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,full-time,7.5,Hyderabad,mid,data engineer,mid,"python, sql, spark, airflow, aws, azure, gcp, ...",0,1,0,...,0,0,0,0,0,0,0,0,0,data engineer
1383,full-time,7.0,Hyderabad,lead,other,senior,"python, sql, excel",0,0,0,...,0,0,0,0,0,0,0,0,0,other
1384,full-time,6.0,Hyderabad,senior,python developer,senior,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,python developer
1385,full-time,5.0,Hyderabad,mid,python developer,mid,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,python developer
1386,full-time,9.0,Hyderabad,mid,python developer,mid,"python, django, flask, fastapi, rest api, git,...",0,0,0,...,0,0,0,0,0,0,0,0,0,python developer

In [23]:
import re
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

df_s = df.copy()

# ============================
# 1) Base categorical cleaning
# ============================
df_s["employment_type"] = df_s["employment_type"].fillna("unknown").astype(str)
df_s["city"] = df_s["city"].fillna("unknown").astype(str)
df_s["clean_role"] = df_s["clean_role"].fillna("other").astype(str)

# Fix seniority
if "clean_seniority" not in df_s.columns:
    df_s["clean_seniority"] = df_s.get("seniority_level", "mid")

df_s["clean_seniority"] = df_s["clean_seniority"].fillna("mid").astype(str)

# numerical seniority
seniority_map = {
    "intern": 0, "trainee": 0,
    "junior": 1, "jr": 1,
    "mid": 2, "middle": 2,
    "senior": 3, "sr": 3,
    "lead": 4,
    "director": 5,
}

df_s["seniority_num"] = df_s["clean_seniority"].str.lower().map(seniority_map).fillna(2)

# primary role
df_s["primary_role"] = (
    df_s["clean_role"].str.split(",").str[0].str.strip().str.lower()
)

# ============================
# 2) City tier feature
# ============================
tier1 = ["bengaluru", "bangalore", "hyderabad", "mumbai", "pune", "gurugram", "delhi", "noida", "chennai"]
tier2 = ["jaipur", "indore", "ahmedabad", "lucknow", "bhopal"]
tier3 = []

def get_city_tier(city):
    c = str(city).lower()
    if c in tier1: return 1
    if c in tier2: return 2
    return 3

df_s["city_tier"] = df_s["city"].apply(get_city_tier)

# ============================
# 3) Skill grouping
# ============================
df_s["skills"] = df_s["skills"].fillna("").astype(str)

def has(pattern, s):
    return int(bool(re.search(pattern, s.lower())))

df_s["has_programming"] = df_s["skills"].apply(lambda s: has(r"python|java|r\b", s))
df_s["has_bigdata"] = df_s["skills"].apply(lambda s: has(r"spark|kafka|hadoop", s))
df_s["has_devops"] = df_s["skills"].apply(lambda s: has(r"docker|kubernetes|airflow", s))
df_s["has_cloud"] = df_s["skills"].apply(lambda s: has(r"aws|azure|gcp", s))
df_s["has_ds"] = df_s["skills"].apply(lambda s: has(r"machine learning|deep learning|pytorch|tensorflow|sklearn", s))
df_s["has_db"] = df_s["skills"].apply(lambda s: has(r"sql|mysql|postgres|nosql", s))
df_s["has_bi"] = df_s["skills"].apply(lambda s: has(r"tableau|power bi|dax", s))

# ============================
# 4) Final feature list
# ============================
features_better = [
    "employment_type",
    "city",
    "primary_role",
    "seniority_num",
    "city_tier",
    "has_programming",
    "has_bigdata",
    "has_devops",
    "has_cloud",
    "has_ds",
    "has_db",
    "has_bi",
]

df_model_s = df_s[features_better + ["salary_avg"]].dropna(subset=["salary_avg"]).copy()

X = df_model_s[features_better]
y = df_model_s["salary_avg"]

cat_features = [0, 1, 2]  # employment_type, city, primary_role

# ============================
# 5) Train-test split
# ============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ============================
# 6) CatBoost Regressor
# ============================
model_better = CatBoostRegressor(
    n_estimators=1500,
    depth=8,
    learning_rate=0.03,
    loss_function="RMSE",
    verbose=200,
    random_seed=42
)

model_better.fit(
    X_train, y_train,
    eval_set=(X_test, y_test),
    cat_features=cat_features,
    use_best_model=True,
    early_stopping_rounds=120
)

preds_better = model_better.predict(X_test)

print("R2 (better features):", r2_score(y_test, preds_better))
print("MAE (better features):", mean_absolute_error(y_test, preds_better))

# ============================
# 7) Salary + Skills Prediction Function
# ============================
def predict_salary_and_skills(employment_type, city, seniority, role):
    skills_required = assign_skills(role)
    s_lower = skills_required.lower()

    row = {
        "employment_type": employment_type,
        "city": city,
        "primary_role": role.lower(),
        "seniority_num": seniority_map.get(seniority.lower(), 2),
        "city_tier": get_city_tier(city),
        "has_programming": has(r"python|java|r\b", s_lower),
        "has_bigdata": has(r"spark|kafka|hadoop", s_lower),
        "has_devops": has(r"docker|kubernetes|airflow", s_lower),
        "has_cloud": has(r"aws|azure|gcp", s_lower),
        "has_ds": has(r"machine learning|deep learning|pytorch|tensorflow|sklearn", s_lower),
        "has_db": has(r"sql|mysql|postgres|nosql", s_lower),
        "has_bi": has(r"tableau|power bi|dax", s_lower),
    }

    df_input = pd.DataFrame([row])[features_better]
    predicted_salary = float(model_better.predict(df_input)[0])
    return predicted_salary, skills_required

0:	learn: 4.0622627	test: 3.6279196	best: 3.6279196 (0)	total: 64ms	remaining: 1m 35s
200:	learn: 3.6031703	test: 3.5686622	best: 3.5162763 (89)	total: 13.4s	remaining: 1m 26s
Stopped by overfitting detector  (120 iterations wait)

bestTest = 3.51627627
bestIteration = 89

Shrink model to first 90 iterations.
R2 (better features): 0.05720650522888848
MAE (better features): 2.4671673666801435

In [24]:
from catboost import CatBoostRegressor
import joblib
import os

os.makedirs("models", exist_ok=True)

# 1) Save CatBoost model as .cbm
model_better.save_model("models/salary_model.cbm")

# 2) Save extra metadata you need for prediction
meta = {
    "features": features_better,      # the list of feature columns you used
    "seniority_map": seniority_map,  # your seniority mapping dict
}

joblib.dump(meta, "models/model_meta.joblib")

print("Model and metadata saved.")

Model and metadata saved.